services:
  app:
    tty: true # docker run -t
    environment:
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
      - REACT_APP_BACKEND_URL=http://localhost:3001/api/persons
    image: phonebook-front-dev
    build:
      context: ./frontend/ # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./frontend/:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    ports:
      - 3000:3000
    container_name: phonebook-front-dev # This will name the container
    depends_on:
      - backend
  backend:
    image: phonebook-back-dev
    build:
      context: ./backend/ # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./backend/:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    ports:
      - 3001:3001
    container_name: phonebook-back-dev # This will name the container
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app # wait for the frontend container to be started
      - backend
